CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stickers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  category ENUM ('FINANCIAL', 'FITNESS', 'HEALTH', 'BUSINESS') NOT NULL,
  frequency ENUM ('DAILY', 'WEEKLY', 'MONTHLY') NOT NULL,
  status ENUM ('ACTIVE', 'INACTIVE', 'DRAFT', 'ON_HOLD') NOT NULL,
  is_public BOOL DEFAULT true,
  is_auto_approval BOOL DEFAULT false,
  user_id INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);